#!/bin/sh

USAGE="usage: $0 [option] src dst
options:
  link      sync with symlinks from 'src' dir to 'dst' dir.
  unlink    remove all 'src' dir symlinks from 'dst' dir."

trap '[ "$?" -ne 0 ] && echo "$USAGE"' EXIT

[ "$#" -lt 1 ] && exit 1

getRelativePath() {
  echo "$(cd $(dirname $1)/$(basename $1); pwd)"
}

query=$1
SRC=$(getRelativePath ${2:-.})
DST=$(getRelativePath ${3:-$HOME})

get_paths() {
  local paths=$(git -C $SRC ls-files --recurse-submodules | grep -E "^\." | grep -vE "^\.git*")
  echo "$paths"
}

DEFAULT="\033[0m"
GREEN="\033[92m"
YELLOW="\033[93m"
BLUE="\033[94m"

link() {
  for path in `get_paths`; do
    local srcpath="$SRC/$path"
    local dstpath="$DST/$path"

    local dstdir=$(dirname $dstpath)
    if [ ! -d $dstdir ]; then
      echo "$BLUE[+] Creating directory: $path$DEFAULT"
      mkdir -p "$dstdir"
    fi

    echo "$GREEN[+] Linking: $path$DEFAULT"
    ln -rsf "$srcpath" "$dstpath"
  done
}

unlink() {
  for path in `get_paths | tac`; do
    local dstpath="$DST/$path"

    if [ -f "$dstpath" ]; then
      echo "$GREEN[+] Unlinking: $path$DEFAULT"
      rm "$dstpath"
    fi

    local dir=$(dirname $dstpath)
    if [ -d $dir ] && [ $(ls "$dir" | wc -l) -eq 0 ]; then
      echo "$YELLOW[+] Removing Empty Directory: $dir$DEFAULT"
      rm -rf "$dir"
    fi
  done
}

case $query in
  "link")   link   ;;
  "unlink") unlink ;;
  *)        exit 1 ;;
esac
