if empty(glob('~/.vim/autoload/plug.vim'))
  exec '!mkdir -p ~/.vim/autoload && curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall
end

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'scrooloose/nerdtree'

Plug 'tpope/vim-fugitive'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'

Plug 'ryanoasis/vim-devicons'
Plug 'Yggdroot/indentLine'

Plug 'vim-airline/vim-airline'

Plug 'lycuid/old-school.vim'

Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'rust-lang/rust.vim'
Plug 'neovimhaskell/haskell-vim'

Plug 'scrooloose/nerdcommenter'

call plug#end()

filetype plugin indent on
set autoindent
set colorcolumn=72                " wrap indicator
set cursorline                    " highlight current line
set nu relativenumber             " line number (relative).
set mouse=a                       " mouse click navigation.
set encoding=utf-8
set et ts=2 sw=2 softtabstop=0
set incsearch                     " highlight search as you type.
set hlsearch                      " highlight search words.
set fileformat=unix
set list listchars=tab:--,eol:¬

"" no swap and backup files.
set nobackup
set nowritebackup
set noswapfile
set noundofile

" colorscheme.
set t_Co=256
set termguicolors
colorscheme old_school

" https://github.com/vim/vim/issues/993#issuecomment-255651605
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"        " set foreground color
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"        " set background color

map <C-w><C-t> :tabnew<CR>

nnoremap ,, :noh<CR>

" edit my vimrc
nnoremap <F6> :e $MYVIMRC<CR>

" reloading
nnoremap <F5> :source $MYVIMRC<CR>

" force of habit (sometimes).
nnoremap <C-s> :w<CR>

" reloading
nnoremap <F11> :Goyo<CR>

" page navigation.
noremap <C-k> <C-y>
noremap <C-j> <C-e>

" code/code-block navigation.
nnoremap <S-k> :m .-2<CR>==
nnoremap <S-j> :m .+1<CR>==
inoremap <S-k> <ESC>:m .-2<CR>==gi
inoremap <S-j> <ESC>:m .+1<CR>==gi
vnoremap <S-k> :m '<-2<CR>gv=gv
vnoremap <S-j> :m '>+1<CR>gv=gv

autocmd BufWritePost *Xresources,*Xdefaults silent! !xrdb %
"
"" Downloaded from: https://github.com/ryanoasis/nerd-fonts/

" needed this setting to be available globally as, although,
" 'if gvim running?' can be determined but, `nvim-qt` cannnot be (yet).
set guifont=TerminessTTF\ NF:h13

"" GVIM settings.
if has("gui_running")

  "" auto fullscreen on gvim
  autocmd GUIEnter * simalt ~x

  "" underscore cursor
  set guicursor+=i:hor20-Cursor/lCursor

  "" ctrl+F1 toggle mebubar
  nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>

  set go-=T  "" REMOVES TOOLBAR
  set go-=r  "" REMOVES RIGHT SCROLLBAR
  set go-=L  "" REMOVES LEFT SCROLLBAR
  set go-=m  "" REMOVES MENUBAR
endif

source ~/.vim/plugins.cfg.d/coc.cfg.vim
source ~/.vim/plugins.cfg.d/airline.cfg.vim
source ~/.vim/plugins.cfg.d/nerdtree.cfg.vim
source ~/.vim/plugins.cfg.d/build_systems.cfg.vim
source ~/.vim/plugins.cfg.d/plugins.cfg.vim

