if empty(glob('~/.vim/autoload/plug.vim'))
  exec '!mkdir -p ~/.vim/autoload && curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall
end

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'ryanoasis/vim-devicons'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'
Plug 'lycuid/old-school.vim'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'scrooloose/nerdcommenter'

call plug#end()

filetype plugin indent on
set autoindent
set colorcolumn=81                " wrap indicator
set cursorline                    " highlight current line
set nu relativenumber             " line number (relative).
set mouse=a                       " mouse click navigation.
set encoding=utf-8
set et ts=2 sw=2 softtabstop=0
set incsearch                     " highlight search as you type.
set hlsearch                      " highlight search words.
set fileformat=unix
set list listchars=tab:--,eol:¬

" copy/paste from system clipboard.
set clipboard=unnamedplus

"" no swap and backup files.
set nobackup
set nowritebackup
set noswapfile
set noundofile

" colorscheme.
set t_Co=256
set termguicolors
colorscheme old_school

" https://github.com/vim/vim/issues/993#issuecomment-255651605
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"        " set foreground color
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"        " set background color

nnoremap <leader>t :tabnew<CR>
nnoremap <leader>, :noh<CR>
" edit vimrc
nnoremap <leader>v :e $MYVIMRC<CR>
" reload vimrc.
nnoremap <leader>r :source $MYVIMRC<CR>
" reloading
nnoremap <F11> :Goyo<CR>
" page navigation.
noremap <C-j> <C-e>
noremap <C-k> <C-y>
noremap <C-h> :bp<CR>
noremap <C-l> :bn<CR>

autocmd Filetype xdefaults autocmd BufWritePost <buffer> silent! !xrdb $XDG_CONFIG_HOME/X11/Xresources
"
" needed this setting to be available globally as, although,
" 'if gvim running?' can be determined but, `nvim-qt` cannnot be (yet).
set guifont=FiraCode\ NF:h11

"" GVIM settings.
if has("gui_running")

  "" auto fullscreen on gvim
  autocmd GUIEnter * simalt ~x

  "" ctrl+F1 toggle mebubar
  nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>

  set go-=T  "" REMOVES TOOLBAR
  set go-=r  "" REMOVES RIGHT SCROLLBAR
  set go-=L  "" REMOVES LEFT SCROLLBAR
  set go-=m  "" REMOVES MENUBAR
endif

runtime vimrc.d/coc.vim
runtime vimrc.d/airline.vim
runtime vimrc.d/nerdtree.vim
runtime vimrc.d/build_systems.vim
runtime vimrc.d/misc.vim

