call plug#begin()

Plug 'lycuid/cluless.vim'
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'Yggdroot/indentLine'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'

if has("nvim")
  Plug 'neovim/nvim-lspconfig'
  Plug 'nvim-treesitter/nvim-treesitter'
  Plug 'norcalli/nvim-colorizer.lua'
endif

call plug#end()

runtime vimrc.d/misc.vim
runtime smallrc
