call plug#begin()

Plug 'lycuid/cluless.vim'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf'
Plug 'scrooloose/nerdcommenter'
Plug 'Yggdroot/indentLine'
Plug 'vim-airline/vim-airline'

if has("nvim")
  Plug 'neovim/nvim-lspconfig'
  Plug 'nvim-treesitter/nvim-treesitter'
  Plug 'norcalli/nvim-colorizer.lua'
  Plug 'lewis6991/gitsigns.nvim'
  Plug 'nvim-treesitter/nvim-treesitter-context'
endif

call plug#end()

runtime vimrc.d/misc.vim
runtime smallrc
