packadd! fzf.vim
packadd! nerdcommenter
packadd! nerdtree
packadd! nerdtree-git-plugin
packadd! vim-devicons
packadd! vim-gitgutter
packadd! indentLine
packadd! vim-airline

runtime vimrc.d/misc.vim
runtime vimrc.d/airline.vim
runtime vimrc.d/nerdtree.vim
runtime smallrc
