#!/bin/sh

set -e
BIN=$1

if $(find . ! -type d | cut -d\/ -f2- | stest -qn "$BIN");
then
  echo "[+] recompiling xmobar."

  temp_dir=$(mktemp -d)
  trap 'rm -rf "$temp_dir"' EXIT TERM INT HUP

  temp_flags=(-odir "$temp_dir" -hidir "$temp_dir")
  # compile options from 'src/Xmobar/App/Compile.hs'.
  build_flags=(-o "$BIN" -dynamic -threaded -i -ilib -fforce-recomp -main-is main -v0)

  ghc --make xmobar.hs "${build_flags[@]}" "${temp_flags[@]}"

  echo "[+] successfully compiled xmobar."
fi

$BIN
