#!/bin/sh

set -e
BIN=$1

if $(find . ! -type d | cut -d\/ -f2- | stest -qn "$BIN");
then
  echo "[+] recompiling xmobar."

  temp_dir=$(mktemp -d)
  trap 'rm -rf "$temp_dir"' EXIT TERM INT HUP

  temp_flags=(-odir "$temp_dir" -hidir "$temp_dir")
  build_flags=(-o "$BIN" -dynamic -threaded -i -ilib -fforce-recomp -v0)

  ghc --make xmobar.hs "${build_flags[@]}" "${temp_flags[@]}"
  strip "$BIN"

  echo "[+] successfully compiled xmobar."
fi

$BIN
