#!/bin/bash

xdir=$(dirname $0)
[ -f "$xdir/Xresources" ] && xrdb -merge "$xdir/Xresources"
xsetroot -cursor_name left_ptr
xset r rate 300 50
xset s on
xset s 165 180
xss-lock -- slock &

mkdir -p "$XDG_RUNTIME_DIR"/pipe
volume '0%' &
dunst &
sxhkd &
picom -b
$HOME/.fehbg &
smolprog-xsetroot &
notify_welcome

STATUS=/tmp/cluless-status${DISPLAY}
[ ! -p ${STATUS} ] && mkfifo ${STATUS}

clubar <${STATUS} &
exec cluless >${STATUS}

# vim: ft=sh
