#!/bin/sh

xrdb -load $XDG_CONFIG_HOME/X11/Xresources

xsetroot -cursor_name left_ptr &  # good'ol left arrow.
xset r rate 300 50 &              # increase x rate.
xautolock &                       # auto lock (configs in Xresources).
dunst &                           # notification daemon.
compton &                         # compositior (for transparency).
sxhkd &                           # hotkey daemon.
$HOME/.fehbg &                    # setting wallpaper.

# This is a fix for https://github.com/xmonad/xmonad/issues/164
[ -e "$HOME/.xmonad" ] && rm -rf $HOME/.xmonad
exec xmonad                       # window manager.

