#!/bin/sh

set -e
BIN=$1

if $(find . ! -type d | cut -d\/ -f2- | stest -qn "$BIN");
then
  echo "[+] recompiling xmonad."

  temp_dir=$(mktemp -d)
  trap 'rm -rf "$temp_dir"' EXIT TERM INT HUP

  temp_flags=(-odir "$temp_dir" -hidir "$temp_dir")
  build_flags=(-o "$BIN" -i -ilib -dynamic -fforce-recomp -main-is main -v0)

  ghc --make xmonad.hs "${build_flags[@]}" "${temp_flags[@]}"

  echo "[+] successfully compiled xmonad."
fi
