#!/bin/sh

set -e
BIN=$1

if $(find . ! -type d | cut -d\/ -f2- | stest -qn "$BIN");
then
  echo "[+] recompiling xmonad."

  temp_dir=$(mktemp -d)
  trap 'rm -rf "$temp_dir"' EXIT TERM INT HUP

  tmp_flags=(-odir "$temp_dir" -hidir "$temp_dir")
  build_flags=(-o "$BIN" -dynamic -i -ilib -fforce-recomp -v0)

  ghc --make xmonad.hs "${build_flags[@]}" "${tmp_flags[@]}"
  strip "$BIN"

  echo "[+] successfully compiled xmonad."
fi
